/// <mls fileReference="_102049_/l2/cafeFlow/web/shared/ws-manager-combo-rules.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowWsManagerComboRulesBase } from './ws-manager-combo-rules.js';
import type { CafeFlowCreateComboRuleInput, CafeFlowDeleteComboRuleInput, CafeFlowQueryComboRulesInput, CafeFlowUpdateComboRuleInput } from '../contracts/ws-manager-combo-rules.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowWsManagerComboRulesBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_queryComboRulesState = Assert<Assignable<typeof page.queryComboRulesState, "idle" | "loading" | "success" | "error">>;
type _State_queryComboRulesComboRuleId = Assert<Assignable<typeof page.queryComboRulesComboRuleId, string | CafeFlowQueryComboRulesInput["comboRuleId"]>>;
type _State_queryComboRulesMenuItemId = Assert<Assignable<typeof page.queryComboRulesMenuItemId, string | CafeFlowQueryComboRulesInput["menuItemId"]>>;
type _State_queryComboRulesName = Assert<Assignable<typeof page.queryComboRulesName, string | CafeFlowQueryComboRulesInput["name"]>>;
type _State_queryComboRulesStatus = Assert<Assignable<typeof page.queryComboRulesStatus, string | CafeFlowQueryComboRulesInput["status"]>>;
type _State_queryComboRulesCreatedAt = Assert<Assignable<typeof page.queryComboRulesCreatedAt, string | CafeFlowQueryComboRulesInput["createdAt"]>>;
type _State_queryComboRulesUpdatedAt = Assert<Assignable<typeof page.queryComboRulesUpdatedAt, string | CafeFlowQueryComboRulesInput["updatedAt"]>>;
type _State_queryComboRulesData = Assert<Assignable<typeof page.queryComboRulesData, unknown[]>>;
type _State_createComboRuleState = Assert<Assignable<typeof page.createComboRuleState, "idle" | "loading" | "success" | "error">>;
type _State_createComboRuleName = Assert<Assignable<typeof page.createComboRuleName, string | CafeFlowCreateComboRuleInput["name"]>>;
type _State_createComboRuleDescription = Assert<Assignable<typeof page.createComboRuleDescription, string | CafeFlowCreateComboRuleInput["description"]>>;
type _State_createComboRulePriceDifference = Assert<Assignable<typeof page.createComboRulePriceDifference, string | CafeFlowCreateComboRuleInput["priceDifference"]>>;
type _State_createComboRuleStatus = Assert<Assignable<typeof page.createComboRuleStatus, string | CafeFlowCreateComboRuleInput["status"]>>;
type _State_updateComboRuleState = Assert<Assignable<typeof page.updateComboRuleState, "idle" | "loading" | "success" | "error">>;
type _State_updateComboRuleName = Assert<Assignable<typeof page.updateComboRuleName, string | CafeFlowUpdateComboRuleInput["name"]>>;
type _State_updateComboRuleDescription = Assert<Assignable<typeof page.updateComboRuleDescription, string | CafeFlowUpdateComboRuleInput["description"]>>;
type _State_updateComboRulePriceDifference = Assert<Assignable<typeof page.updateComboRulePriceDifference, string | CafeFlowUpdateComboRuleInput["priceDifference"]>>;
type _State_updateComboRuleStatus = Assert<Assignable<typeof page.updateComboRuleStatus, string | CafeFlowUpdateComboRuleInput["status"]>>;
type _State_deleteComboRuleState = Assert<Assignable<typeof page.deleteComboRuleState, "idle" | "loading" | "success" | "error">>;
type _State_deleteComboRuleComboRuleId = Assert<Assignable<typeof page.deleteComboRuleComboRuleId, string | CafeFlowDeleteComboRuleInput["comboRuleId"]>>;
type _State_deleteComboRuleMenuItemId = Assert<Assignable<typeof page.deleteComboRuleMenuItemId, string | CafeFlowDeleteComboRuleInput["menuItemId"]>>;
type _State_deleteComboRuleName = Assert<Assignable<typeof page.deleteComboRuleName, string | CafeFlowDeleteComboRuleInput["name"]>>;
type _State_deleteComboRuleDescription = Assert<Assignable<typeof page.deleteComboRuleDescription, string | CafeFlowDeleteComboRuleInput["description"]>>;
type _State_deleteComboRulePriceDifference = Assert<Assignable<typeof page.deleteComboRulePriceDifference, string | CafeFlowDeleteComboRuleInput["priceDifference"]>>;
type _State_deleteComboRuleStatus = Assert<Assignable<typeof page.deleteComboRuleStatus, string | CafeFlowDeleteComboRuleInput["status"]>>;
type _State_OutputCreateComboRule = Assert<Assignable<typeof page.OutputCreateComboRule, unknown>>;
type _State_OutputUpdateComboRule = Assert<Assignable<typeof page.OutputUpdateComboRule, unknown>>;
type _State_OutputDeleteComboRule = Assert<Assignable<typeof page.OutputDeleteComboRule, unknown>>;
type _Action_loadQueryComboRules = Assert<Assignable<typeof page.loadQueryComboRules, (...args: any[]) => Promise<void>>>;
type _Handler_handleQueryComboRulesClick = Assert<Assignable<typeof page.handleQueryComboRulesClick, (...args: any[]) => void>>;
type _Action_createComboRule = Assert<Assignable<typeof page.createComboRule, (...args: any[]) => Promise<void>>>;
type _Handler_handleCreateComboRuleClick = Assert<Assignable<typeof page.handleCreateComboRuleClick, (...args: any[]) => void>>;
type _Action_updateComboRule = Assert<Assignable<typeof page.updateComboRule, (...args: any[]) => Promise<void>>>;
type _Handler_handleUpdateComboRuleClick = Assert<Assignable<typeof page.handleUpdateComboRuleClick, (...args: any[]) => void>>;
type _Action_deleteComboRule = Assert<Assignable<typeof page.deleteComboRule, (...args: any[]) => Promise<void>>>;
type _Handler_handleDeleteComboRuleClick = Assert<Assignable<typeof page.handleDeleteComboRuleClick, (...args: any[]) => void>>;
type _Action_setQueryComboRulesComboRuleId = Assert<Assignable<typeof page.setQueryComboRulesComboRuleId, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesComboRuleIdChange = Assert<Assignable<typeof page.handleQueryComboRulesComboRuleIdChange, (...args: any[]) => void>>;
type _Action_setQueryComboRulesMenuItemId = Assert<Assignable<typeof page.setQueryComboRulesMenuItemId, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesMenuItemIdChange = Assert<Assignable<typeof page.handleQueryComboRulesMenuItemIdChange, (...args: any[]) => void>>;
type _Action_setQueryComboRulesName = Assert<Assignable<typeof page.setQueryComboRulesName, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesNameChange = Assert<Assignable<typeof page.handleQueryComboRulesNameChange, (...args: any[]) => void>>;
type _Action_setQueryComboRulesStatus = Assert<Assignable<typeof page.setQueryComboRulesStatus, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesStatusChange = Assert<Assignable<typeof page.handleQueryComboRulesStatusChange, (...args: any[]) => void>>;
type _Action_setQueryComboRulesCreatedAt = Assert<Assignable<typeof page.setQueryComboRulesCreatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesCreatedAtChange = Assert<Assignable<typeof page.handleQueryComboRulesCreatedAtChange, (...args: any[]) => void>>;
type _Action_setQueryComboRulesUpdatedAt = Assert<Assignable<typeof page.setQueryComboRulesUpdatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryComboRulesUpdatedAtChange = Assert<Assignable<typeof page.handleQueryComboRulesUpdatedAtChange, (...args: any[]) => void>>;
type _Action_setCreateComboRuleName = Assert<Assignable<typeof page.setCreateComboRuleName, (...args: any[]) => void>>;
type _Handler_handleCreateComboRuleNameChange = Assert<Assignable<typeof page.handleCreateComboRuleNameChange, (...args: any[]) => void>>;
type _Action_setCreateComboRuleDescription = Assert<Assignable<typeof page.setCreateComboRuleDescription, (...args: any[]) => void>>;
type _Handler_handleCreateComboRuleDescriptionChange = Assert<Assignable<typeof page.handleCreateComboRuleDescriptionChange, (...args: any[]) => void>>;
type _Action_setCreateComboRulePriceDifference = Assert<Assignable<typeof page.setCreateComboRulePriceDifference, (...args: any[]) => void>>;
type _Handler_handleCreateComboRulePriceDifferenceChange = Assert<Assignable<typeof page.handleCreateComboRulePriceDifferenceChange, (...args: any[]) => void>>;
type _Action_setCreateComboRuleStatus = Assert<Assignable<typeof page.setCreateComboRuleStatus, (...args: any[]) => void>>;
type _Handler_handleCreateComboRuleStatusChange = Assert<Assignable<typeof page.handleCreateComboRuleStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateComboRuleName = Assert<Assignable<typeof page.setUpdateComboRuleName, (...args: any[]) => void>>;
type _Handler_handleUpdateComboRuleNameChange = Assert<Assignable<typeof page.handleUpdateComboRuleNameChange, (...args: any[]) => void>>;
type _Action_setUpdateComboRuleDescription = Assert<Assignable<typeof page.setUpdateComboRuleDescription, (...args: any[]) => void>>;
type _Handler_handleUpdateComboRuleDescriptionChange = Assert<Assignable<typeof page.handleUpdateComboRuleDescriptionChange, (...args: any[]) => void>>;
type _Action_setUpdateComboRulePriceDifference = Assert<Assignable<typeof page.setUpdateComboRulePriceDifference, (...args: any[]) => void>>;
type _Handler_handleUpdateComboRulePriceDifferenceChange = Assert<Assignable<typeof page.handleUpdateComboRulePriceDifferenceChange, (...args: any[]) => void>>;
type _Action_setUpdateComboRuleStatus = Assert<Assignable<typeof page.setUpdateComboRuleStatus, (...args: any[]) => void>>;
type _Handler_handleUpdateComboRuleStatusChange = Assert<Assignable<typeof page.handleUpdateComboRuleStatusChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRuleComboRuleId = Assert<Assignable<typeof page.setDeleteComboRuleComboRuleId, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRuleComboRuleIdChange = Assert<Assignable<typeof page.handleDeleteComboRuleComboRuleIdChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRuleMenuItemId = Assert<Assignable<typeof page.setDeleteComboRuleMenuItemId, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRuleMenuItemIdChange = Assert<Assignable<typeof page.handleDeleteComboRuleMenuItemIdChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRuleName = Assert<Assignable<typeof page.setDeleteComboRuleName, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRuleNameChange = Assert<Assignable<typeof page.handleDeleteComboRuleNameChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRuleDescription = Assert<Assignable<typeof page.setDeleteComboRuleDescription, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRuleDescriptionChange = Assert<Assignable<typeof page.handleDeleteComboRuleDescriptionChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRulePriceDifference = Assert<Assignable<typeof page.setDeleteComboRulePriceDifference, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRulePriceDifferenceChange = Assert<Assignable<typeof page.handleDeleteComboRulePriceDifferenceChange, (...args: any[]) => void>>;
type _Action_setDeleteComboRuleStatus = Assert<Assignable<typeof page.setDeleteComboRuleStatus, (...args: any[]) => void>>;
type _Handler_handleDeleteComboRuleStatusChange = Assert<Assignable<typeof page.handleDeleteComboRuleStatusChange, (...args: any[]) => void>>;

export {};