/// <mls fileReference="_102049_/l2/cafeFlow/web/shared/ws-manager-stock-items.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowWsManagerStockItemsBase } from './ws-manager-stock-items.js';
import type { CafeFlowCreateStockItemInput, CafeFlowDeleteStockItemInput, CafeFlowQueryStockItemsInput, CafeFlowUpdateStockItemInput } from '../contracts/ws-manager-stock-items.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowWsManagerStockItemsBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_queryStockItemsState = Assert<Assignable<typeof page.queryStockItemsState, "idle" | "loading" | "success" | "error">>;
type _State_queryStockItemsStockItemId = Assert<Assignable<typeof page.queryStockItemsStockItemId, string | CafeFlowQueryStockItemsInput["stockItemId"]>>;
type _State_queryStockItemsName = Assert<Assignable<typeof page.queryStockItemsName, string | CafeFlowQueryStockItemsInput["name"]>>;
type _State_queryStockItemsStatus = Assert<Assignable<typeof page.queryStockItemsStatus, string | CafeFlowQueryStockItemsInput["status"]>>;
type _State_queryStockItemsCreatedAt = Assert<Assignable<typeof page.queryStockItemsCreatedAt, string | CafeFlowQueryStockItemsInput["createdAt"]>>;
type _State_queryStockItemsUpdatedAt = Assert<Assignable<typeof page.queryStockItemsUpdatedAt, string | CafeFlowQueryStockItemsInput["updatedAt"]>>;
type _State_queryStockItemsData = Assert<Assignable<typeof page.queryStockItemsData, unknown[]>>;
type _State_createStockItemState = Assert<Assignable<typeof page.createStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_createStockItemName = Assert<Assignable<typeof page.createStockItemName, string | CafeFlowCreateStockItemInput["name"]>>;
type _State_createStockItemUnitOfMeasure = Assert<Assignable<typeof page.createStockItemUnitOfMeasure, string | CafeFlowCreateStockItemInput["unitOfMeasure"]>>;
type _State_createStockItemMinimumQuantity = Assert<Assignable<typeof page.createStockItemMinimumQuantity, string | CafeFlowCreateStockItemInput["minimumQuantity"]>>;
type _State_createStockItemStatus = Assert<Assignable<typeof page.createStockItemStatus, string | CafeFlowCreateStockItemInput["status"]>>;
type _State_updateStockItemState = Assert<Assignable<typeof page.updateStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_updateStockItemName = Assert<Assignable<typeof page.updateStockItemName, string | CafeFlowUpdateStockItemInput["name"]>>;
type _State_updateStockItemUnitOfMeasure = Assert<Assignable<typeof page.updateStockItemUnitOfMeasure, string | CafeFlowUpdateStockItemInput["unitOfMeasure"]>>;
type _State_updateStockItemMinimumQuantity = Assert<Assignable<typeof page.updateStockItemMinimumQuantity, string | CafeFlowUpdateStockItemInput["minimumQuantity"]>>;
type _State_updateStockItemStatus = Assert<Assignable<typeof page.updateStockItemStatus, string | CafeFlowUpdateStockItemInput["status"]>>;
type _State_deleteStockItemState = Assert<Assignable<typeof page.deleteStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_deleteStockItemStockItemId = Assert<Assignable<typeof page.deleteStockItemStockItemId, string | CafeFlowDeleteStockItemInput["stockItemId"]>>;
type _State_deleteStockItemName = Assert<Assignable<typeof page.deleteStockItemName, string | CafeFlowDeleteStockItemInput["name"]>>;
type _State_deleteStockItemUnitOfMeasure = Assert<Assignable<typeof page.deleteStockItemUnitOfMeasure, string | CafeFlowDeleteStockItemInput["unitOfMeasure"]>>;
type _State_deleteStockItemMinimumQuantity = Assert<Assignable<typeof page.deleteStockItemMinimumQuantity, string | CafeFlowDeleteStockItemInput["minimumQuantity"]>>;
type _State_deleteStockItemStatus = Assert<Assignable<typeof page.deleteStockItemStatus, string | CafeFlowDeleteStockItemInput["status"]>>;
type _Action_loadQueryStockItems = Assert<Assignable<typeof page.loadQueryStockItems, (...args: any[]) => Promise<void>>>;
type _Handler_handleQueryStockItemsClick = Assert<Assignable<typeof page.handleQueryStockItemsClick, (...args: any[]) => void>>;
type _Action_createStockItem = Assert<Assignable<typeof page.createStockItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleCreateStockItemClick = Assert<Assignable<typeof page.handleCreateStockItemClick, (...args: any[]) => void>>;
type _Action_updateStockItem = Assert<Assignable<typeof page.updateStockItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleUpdateStockItemClick = Assert<Assignable<typeof page.handleUpdateStockItemClick, (...args: any[]) => void>>;
type _Action_deleteStockItem = Assert<Assignable<typeof page.deleteStockItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleDeleteStockItemClick = Assert<Assignable<typeof page.handleDeleteStockItemClick, (...args: any[]) => void>>;
type _Action_setQueryStockItemsStockItemId = Assert<Assignable<typeof page.setQueryStockItemsStockItemId, (...args: any[]) => void>>;
type _Handler_handleQueryStockItemsStockItemIdChange = Assert<Assignable<typeof page.handleQueryStockItemsStockItemIdChange, (...args: any[]) => void>>;
type _Action_setQueryStockItemsName = Assert<Assignable<typeof page.setQueryStockItemsName, (...args: any[]) => void>>;
type _Handler_handleQueryStockItemsNameChange = Assert<Assignable<typeof page.handleQueryStockItemsNameChange, (...args: any[]) => void>>;
type _Action_setQueryStockItemsStatus = Assert<Assignable<typeof page.setQueryStockItemsStatus, (...args: any[]) => void>>;
type _Handler_handleQueryStockItemsStatusChange = Assert<Assignable<typeof page.handleQueryStockItemsStatusChange, (...args: any[]) => void>>;
type _Action_setQueryStockItemsCreatedAt = Assert<Assignable<typeof page.setQueryStockItemsCreatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryStockItemsCreatedAtChange = Assert<Assignable<typeof page.handleQueryStockItemsCreatedAtChange, (...args: any[]) => void>>;
type _Action_setQueryStockItemsUpdatedAt = Assert<Assignable<typeof page.setQueryStockItemsUpdatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryStockItemsUpdatedAtChange = Assert<Assignable<typeof page.handleQueryStockItemsUpdatedAtChange, (...args: any[]) => void>>;
type _Action_setCreateStockItemName = Assert<Assignable<typeof page.setCreateStockItemName, (...args: any[]) => void>>;
type _Handler_handleCreateStockItemNameChange = Assert<Assignable<typeof page.handleCreateStockItemNameChange, (...args: any[]) => void>>;
type _Action_setCreateStockItemUnitOfMeasure = Assert<Assignable<typeof page.setCreateStockItemUnitOfMeasure, (...args: any[]) => void>>;
type _Handler_handleCreateStockItemUnitOfMeasureChange = Assert<Assignable<typeof page.handleCreateStockItemUnitOfMeasureChange, (...args: any[]) => void>>;
type _Action_setCreateStockItemMinimumQuantity = Assert<Assignable<typeof page.setCreateStockItemMinimumQuantity, (...args: any[]) => void>>;
type _Handler_handleCreateStockItemMinimumQuantityChange = Assert<Assignable<typeof page.handleCreateStockItemMinimumQuantityChange, (...args: any[]) => void>>;
type _Action_setCreateStockItemStatus = Assert<Assignable<typeof page.setCreateStockItemStatus, (...args: any[]) => void>>;
type _Handler_handleCreateStockItemStatusChange = Assert<Assignable<typeof page.handleCreateStockItemStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateStockItemName = Assert<Assignable<typeof page.setUpdateStockItemName, (...args: any[]) => void>>;
type _Handler_handleUpdateStockItemNameChange = Assert<Assignable<typeof page.handleUpdateStockItemNameChange, (...args: any[]) => void>>;
type _Action_setUpdateStockItemUnitOfMeasure = Assert<Assignable<typeof page.setUpdateStockItemUnitOfMeasure, (...args: any[]) => void>>;
type _Handler_handleUpdateStockItemUnitOfMeasureChange = Assert<Assignable<typeof page.handleUpdateStockItemUnitOfMeasureChange, (...args: any[]) => void>>;
type _Action_setUpdateStockItemMinimumQuantity = Assert<Assignable<typeof page.setUpdateStockItemMinimumQuantity, (...args: any[]) => void>>;
type _Handler_handleUpdateStockItemMinimumQuantityChange = Assert<Assignable<typeof page.handleUpdateStockItemMinimumQuantityChange, (...args: any[]) => void>>;
type _Action_setUpdateStockItemStatus = Assert<Assignable<typeof page.setUpdateStockItemStatus, (...args: any[]) => void>>;
type _Handler_handleUpdateStockItemStatusChange = Assert<Assignable<typeof page.handleUpdateStockItemStatusChange, (...args: any[]) => void>>;
type _Action_setDeleteStockItemStockItemId = Assert<Assignable<typeof page.setDeleteStockItemStockItemId, (...args: any[]) => void>>;
type _Handler_handleDeleteStockItemStockItemIdChange = Assert<Assignable<typeof page.handleDeleteStockItemStockItemIdChange, (...args: any[]) => void>>;
type _Action_setDeleteStockItemName = Assert<Assignable<typeof page.setDeleteStockItemName, (...args: any[]) => void>>;
type _Handler_handleDeleteStockItemNameChange = Assert<Assignable<typeof page.handleDeleteStockItemNameChange, (...args: any[]) => void>>;
type _Action_setDeleteStockItemUnitOfMeasure = Assert<Assignable<typeof page.setDeleteStockItemUnitOfMeasure, (...args: any[]) => void>>;
type _Handler_handleDeleteStockItemUnitOfMeasureChange = Assert<Assignable<typeof page.handleDeleteStockItemUnitOfMeasureChange, (...args: any[]) => void>>;
type _Action_setDeleteStockItemMinimumQuantity = Assert<Assignable<typeof page.setDeleteStockItemMinimumQuantity, (...args: any[]) => void>>;
type _Handler_handleDeleteStockItemMinimumQuantityChange = Assert<Assignable<typeof page.handleDeleteStockItemMinimumQuantityChange, (...args: any[]) => void>>;
type _Action_setDeleteStockItemStatus = Assert<Assignable<typeof page.setDeleteStockItemStatus, (...args: any[]) => void>>;
type _Handler_handleDeleteStockItemStatusChange = Assert<Assignable<typeof page.handleDeleteStockItemStatusChange, (...args: any[]) => void>>;

export {};