/// <mls fileReference="_102049_/l2/cafeFlow/web/shared/ws-manager-shift.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowWsManagerShiftBase } from './ws-manager-shift.js';
import type { CafeFlowCloseShiftInput, CafeFlowGenerateShiftClosingReportInput, CafeFlowOpenShiftInput, CafeFlowQueryDashboardInput } from '../contracts/ws-manager-shift.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowWsManagerShiftBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_openShiftState = Assert<Assignable<typeof page.openShiftState, "idle" | "loading" | "success" | "error">>;
type _State_openShiftStatus = Assert<Assignable<typeof page.openShiftStatus, string | CafeFlowOpenShiftInput["status"]>>;
type _State_openShiftOpenedAt = Assert<Assignable<typeof page.openShiftOpenedAt, string | CafeFlowOpenShiftInput["openedAt"]>>;
type _State_openShiftClosedAt = Assert<Assignable<typeof page.openShiftClosedAt, string | CafeFlowOpenShiftInput["closedAt"]>>;
type _State_queryDashboardState = Assert<Assignable<typeof page.queryDashboardState, "idle" | "loading" | "success" | "error">>;
type _State_queryDashboardShiftId = Assert<Assignable<typeof page.queryDashboardShiftId, string | CafeFlowQueryDashboardInput["shiftId"]>>;
type _State_queryDashboardStatus = Assert<Assignable<typeof page.queryDashboardStatus, string | CafeFlowQueryDashboardInput["status"]>>;
type _State_queryDashboardOpenedAt = Assert<Assignable<typeof page.queryDashboardOpenedAt, string | CafeFlowQueryDashboardInput["openedAt"]>>;
type _State_queryDashboardClosedAt = Assert<Assignable<typeof page.queryDashboardClosedAt, string | CafeFlowQueryDashboardInput["closedAt"]>>;
type _State_queryDashboardCreatedAt = Assert<Assignable<typeof page.queryDashboardCreatedAt, string | CafeFlowQueryDashboardInput["createdAt"]>>;
type _State_queryDashboardUpdatedAt = Assert<Assignable<typeof page.queryDashboardUpdatedAt, string | CafeFlowQueryDashboardInput["updatedAt"]>>;
type _State_queryDashboardData = Assert<Assignable<typeof page.queryDashboardData, unknown[]>>;
type _State_closeShiftState = Assert<Assignable<typeof page.closeShiftState, "idle" | "loading" | "success" | "error">>;
type _State_closeShiftStatus = Assert<Assignable<typeof page.closeShiftStatus, string | CafeFlowCloseShiftInput["status"]>>;
type _State_closeShiftClosedAt = Assert<Assignable<typeof page.closeShiftClosedAt, string | CafeFlowCloseShiftInput["closedAt"]>>;
type _State_generateShiftClosingReportState = Assert<Assignable<typeof page.generateShiftClosingReportState, "idle" | "loading" | "success" | "error">>;
type _State_generateShiftClosingReportShiftId = Assert<Assignable<typeof page.generateShiftClosingReportShiftId, string | CafeFlowGenerateShiftClosingReportInput["shiftId"]>>;
type _State_generateShiftClosingReportStatus = Assert<Assignable<typeof page.generateShiftClosingReportStatus, string | CafeFlowGenerateShiftClosingReportInput["status"]>>;
type _State_generateShiftClosingReportOpenedAt = Assert<Assignable<typeof page.generateShiftClosingReportOpenedAt, string | CafeFlowGenerateShiftClosingReportInput["openedAt"]>>;
type _State_generateShiftClosingReportClosedAt = Assert<Assignable<typeof page.generateShiftClosingReportClosedAt, string | CafeFlowGenerateShiftClosingReportInput["closedAt"]>>;
type _State_generateShiftClosingReportCreatedAt = Assert<Assignable<typeof page.generateShiftClosingReportCreatedAt, string | CafeFlowGenerateShiftClosingReportInput["createdAt"]>>;
type _State_generateShiftClosingReportUpdatedAt = Assert<Assignable<typeof page.generateShiftClosingReportUpdatedAt, string | CafeFlowGenerateShiftClosingReportInput["updatedAt"]>>;
type _State_generateShiftClosingReportData = Assert<Assignable<typeof page.generateShiftClosingReportData, unknown[]>>;
type _Action_openShift = Assert<Assignable<typeof page.openShift, (...args: any[]) => Promise<void>>>;
type _Handler_handleOpenShiftClick = Assert<Assignable<typeof page.handleOpenShiftClick, (...args: any[]) => void>>;
type _Action_loadQueryDashboard = Assert<Assignable<typeof page.loadQueryDashboard, (...args: any[]) => Promise<void>>>;
type _Handler_handleQueryDashboardClick = Assert<Assignable<typeof page.handleQueryDashboardClick, (...args: any[]) => void>>;
type _Action_closeShift = Assert<Assignable<typeof page.closeShift, (...args: any[]) => Promise<void>>>;
type _Handler_handleCloseShiftClick = Assert<Assignable<typeof page.handleCloseShiftClick, (...args: any[]) => void>>;
type _Action_loadGenerateShiftClosingReport = Assert<Assignable<typeof page.loadGenerateShiftClosingReport, (...args: any[]) => Promise<void>>>;
type _Handler_handleGenerateShiftClosingReportClick = Assert<Assignable<typeof page.handleGenerateShiftClosingReportClick, (...args: any[]) => void>>;
type _Action_setOpenShiftStatus = Assert<Assignable<typeof page.setOpenShiftStatus, (...args: any[]) => void>>;
type _Handler_handleOpenShiftStatusChange = Assert<Assignable<typeof page.handleOpenShiftStatusChange, (...args: any[]) => void>>;
type _Action_setOpenShiftOpenedAt = Assert<Assignable<typeof page.setOpenShiftOpenedAt, (...args: any[]) => void>>;
type _Handler_handleOpenShiftOpenedAtChange = Assert<Assignable<typeof page.handleOpenShiftOpenedAtChange, (...args: any[]) => void>>;
type _Action_setOpenShiftClosedAt = Assert<Assignable<typeof page.setOpenShiftClosedAt, (...args: any[]) => void>>;
type _Handler_handleOpenShiftClosedAtChange = Assert<Assignable<typeof page.handleOpenShiftClosedAtChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardShiftId = Assert<Assignable<typeof page.setQueryDashboardShiftId, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardShiftIdChange = Assert<Assignable<typeof page.handleQueryDashboardShiftIdChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardStatus = Assert<Assignable<typeof page.setQueryDashboardStatus, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardStatusChange = Assert<Assignable<typeof page.handleQueryDashboardStatusChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardOpenedAt = Assert<Assignable<typeof page.setQueryDashboardOpenedAt, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardOpenedAtChange = Assert<Assignable<typeof page.handleQueryDashboardOpenedAtChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardClosedAt = Assert<Assignable<typeof page.setQueryDashboardClosedAt, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardClosedAtChange = Assert<Assignable<typeof page.handleQueryDashboardClosedAtChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardCreatedAt = Assert<Assignable<typeof page.setQueryDashboardCreatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardCreatedAtChange = Assert<Assignable<typeof page.handleQueryDashboardCreatedAtChange, (...args: any[]) => void>>;
type _Action_setQueryDashboardUpdatedAt = Assert<Assignable<typeof page.setQueryDashboardUpdatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryDashboardUpdatedAtChange = Assert<Assignable<typeof page.handleQueryDashboardUpdatedAtChange, (...args: any[]) => void>>;
type _Action_setCloseShiftStatus = Assert<Assignable<typeof page.setCloseShiftStatus, (...args: any[]) => void>>;
type _Handler_handleCloseShiftStatusChange = Assert<Assignable<typeof page.handleCloseShiftStatusChange, (...args: any[]) => void>>;
type _Action_setCloseShiftClosedAt = Assert<Assignable<typeof page.setCloseShiftClosedAt, (...args: any[]) => void>>;
type _Handler_handleCloseShiftClosedAtChange = Assert<Assignable<typeof page.handleCloseShiftClosedAtChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportShiftId = Assert<Assignable<typeof page.setGenerateShiftClosingReportShiftId, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportShiftIdChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportShiftIdChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportStatus = Assert<Assignable<typeof page.setGenerateShiftClosingReportStatus, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportStatusChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportStatusChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportOpenedAt = Assert<Assignable<typeof page.setGenerateShiftClosingReportOpenedAt, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportOpenedAtChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportOpenedAtChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportClosedAt = Assert<Assignable<typeof page.setGenerateShiftClosingReportClosedAt, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportClosedAtChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportClosedAtChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportCreatedAt = Assert<Assignable<typeof page.setGenerateShiftClosingReportCreatedAt, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportCreatedAtChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportCreatedAtChange, (...args: any[]) => void>>;
type _Action_setGenerateShiftClosingReportUpdatedAt = Assert<Assignable<typeof page.setGenerateShiftClosingReportUpdatedAt, (...args: any[]) => void>>;
type _Handler_handleGenerateShiftClosingReportUpdatedAtChange = Assert<Assignable<typeof page.handleGenerateShiftClosingReportUpdatedAtChange, (...args: any[]) => void>>;

export {};