/// <mls fileReference="_102049_/l2/cafeFlow/web/shared/ws-manager-menu.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowWsManagerMenuBase } from './ws-manager-menu.js';
import type { CafeFlowCreateMenuItemInput, CafeFlowDeleteMenuItemInput, CafeFlowQueryMenuItemsInput, CafeFlowUpdateMenuItemInput } from '../contracts/ws-manager-menu.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowWsManagerMenuBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_queryMenuItemsState = Assert<Assignable<typeof page.queryMenuItemsState, "idle" | "loading" | "success" | "error">>;
type _State_queryMenuItemsMenuItemId = Assert<Assignable<typeof page.queryMenuItemsMenuItemId, string | CafeFlowQueryMenuItemsInput["menuItemId"]>>;
type _State_queryMenuItemsName = Assert<Assignable<typeof page.queryMenuItemsName, string | CafeFlowQueryMenuItemsInput["name"]>>;
type _State_queryMenuItemsCategory = Assert<Assignable<typeof page.queryMenuItemsCategory, string | CafeFlowQueryMenuItemsInput["category"]>>;
type _State_queryMenuItemsStatus = Assert<Assignable<typeof page.queryMenuItemsStatus, string | CafeFlowQueryMenuItemsInput["status"]>>;
type _State_queryMenuItemsCreatedAt = Assert<Assignable<typeof page.queryMenuItemsCreatedAt, string | CafeFlowQueryMenuItemsInput["createdAt"]>>;
type _State_queryMenuItemsUpdatedAt = Assert<Assignable<typeof page.queryMenuItemsUpdatedAt, string | CafeFlowQueryMenuItemsInput["updatedAt"]>>;
type _State_queryMenuItemsData = Assert<Assignable<typeof page.queryMenuItemsData, unknown[]>>;
type _State_createMenuItemState = Assert<Assignable<typeof page.createMenuItemState, "idle" | "loading" | "success" | "error">>;
type _State_createMenuItemName = Assert<Assignable<typeof page.createMenuItemName, string | CafeFlowCreateMenuItemInput["name"]>>;
type _State_createMenuItemCategory = Assert<Assignable<typeof page.createMenuItemCategory, string | CafeFlowCreateMenuItemInput["category"]>>;
type _State_createMenuItemPrice = Assert<Assignable<typeof page.createMenuItemPrice, string | CafeFlowCreateMenuItemInput["price"]>>;
type _State_createMenuItemDescription = Assert<Assignable<typeof page.createMenuItemDescription, string | CafeFlowCreateMenuItemInput["description"]>>;
type _State_createMenuItemStatus = Assert<Assignable<typeof page.createMenuItemStatus, string | CafeFlowCreateMenuItemInput["status"]>>;
type _State_updateMenuItemState = Assert<Assignable<typeof page.updateMenuItemState, "idle" | "loading" | "success" | "error">>;
type _State_updateMenuItemName = Assert<Assignable<typeof page.updateMenuItemName, string | CafeFlowUpdateMenuItemInput["name"]>>;
type _State_updateMenuItemCategory = Assert<Assignable<typeof page.updateMenuItemCategory, string | CafeFlowUpdateMenuItemInput["category"]>>;
type _State_updateMenuItemPrice = Assert<Assignable<typeof page.updateMenuItemPrice, string | CafeFlowUpdateMenuItemInput["price"]>>;
type _State_updateMenuItemDescription = Assert<Assignable<typeof page.updateMenuItemDescription, string | CafeFlowUpdateMenuItemInput["description"]>>;
type _State_updateMenuItemStatus = Assert<Assignable<typeof page.updateMenuItemStatus, string | CafeFlowUpdateMenuItemInput["status"]>>;
type _State_deleteMenuItemState = Assert<Assignable<typeof page.deleteMenuItemState, "idle" | "loading" | "success" | "error">>;
type _State_deleteMenuItemMenuItemId = Assert<Assignable<typeof page.deleteMenuItemMenuItemId, string | CafeFlowDeleteMenuItemInput["menuItemId"]>>;
type _State_deleteMenuItemName = Assert<Assignable<typeof page.deleteMenuItemName, string | CafeFlowDeleteMenuItemInput["name"]>>;
type _State_deleteMenuItemCategory = Assert<Assignable<typeof page.deleteMenuItemCategory, string | CafeFlowDeleteMenuItemInput["category"]>>;
type _State_deleteMenuItemPrice = Assert<Assignable<typeof page.deleteMenuItemPrice, string | CafeFlowDeleteMenuItemInput["price"]>>;
type _State_deleteMenuItemDescription = Assert<Assignable<typeof page.deleteMenuItemDescription, string | CafeFlowDeleteMenuItemInput["description"]>>;
type _State_deleteMenuItemStatus = Assert<Assignable<typeof page.deleteMenuItemStatus, string | CafeFlowDeleteMenuItemInput["status"]>>;
type _Action_loadQueryMenuItems = Assert<Assignable<typeof page.loadQueryMenuItems, (...args: any[]) => Promise<void>>>;
type _Handler_handleQueryMenuItemsClick = Assert<Assignable<typeof page.handleQueryMenuItemsClick, (...args: any[]) => void>>;
type _Action_createMenuItem = Assert<Assignable<typeof page.createMenuItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleCreateMenuItemClick = Assert<Assignable<typeof page.handleCreateMenuItemClick, (...args: any[]) => void>>;
type _Action_updateMenuItem = Assert<Assignable<typeof page.updateMenuItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleUpdateMenuItemClick = Assert<Assignable<typeof page.handleUpdateMenuItemClick, (...args: any[]) => void>>;
type _Action_deleteMenuItem = Assert<Assignable<typeof page.deleteMenuItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleDeleteMenuItemClick = Assert<Assignable<typeof page.handleDeleteMenuItemClick, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsMenuItemId = Assert<Assignable<typeof page.setQueryMenuItemsMenuItemId, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsMenuItemIdChange = Assert<Assignable<typeof page.handleQueryMenuItemsMenuItemIdChange, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsName = Assert<Assignable<typeof page.setQueryMenuItemsName, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsNameChange = Assert<Assignable<typeof page.handleQueryMenuItemsNameChange, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsCategory = Assert<Assignable<typeof page.setQueryMenuItemsCategory, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsCategoryChange = Assert<Assignable<typeof page.handleQueryMenuItemsCategoryChange, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsStatus = Assert<Assignable<typeof page.setQueryMenuItemsStatus, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsStatusChange = Assert<Assignable<typeof page.handleQueryMenuItemsStatusChange, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsCreatedAt = Assert<Assignable<typeof page.setQueryMenuItemsCreatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsCreatedAtChange = Assert<Assignable<typeof page.handleQueryMenuItemsCreatedAtChange, (...args: any[]) => void>>;
type _Action_setQueryMenuItemsUpdatedAt = Assert<Assignable<typeof page.setQueryMenuItemsUpdatedAt, (...args: any[]) => void>>;
type _Handler_handleQueryMenuItemsUpdatedAtChange = Assert<Assignable<typeof page.handleQueryMenuItemsUpdatedAtChange, (...args: any[]) => void>>;
type _Action_setCreateMenuItemName = Assert<Assignable<typeof page.setCreateMenuItemName, (...args: any[]) => void>>;
type _Handler_handleCreateMenuItemNameChange = Assert<Assignable<typeof page.handleCreateMenuItemNameChange, (...args: any[]) => void>>;
type _Action_setCreateMenuItemCategory = Assert<Assignable<typeof page.setCreateMenuItemCategory, (...args: any[]) => void>>;
type _Handler_handleCreateMenuItemCategoryChange = Assert<Assignable<typeof page.handleCreateMenuItemCategoryChange, (...args: any[]) => void>>;
type _Action_setCreateMenuItemPrice = Assert<Assignable<typeof page.setCreateMenuItemPrice, (...args: any[]) => void>>;
type _Handler_handleCreateMenuItemPriceChange = Assert<Assignable<typeof page.handleCreateMenuItemPriceChange, (...args: any[]) => void>>;
type _Action_setCreateMenuItemDescription = Assert<Assignable<typeof page.setCreateMenuItemDescription, (...args: any[]) => void>>;
type _Handler_handleCreateMenuItemDescriptionChange = Assert<Assignable<typeof page.handleCreateMenuItemDescriptionChange, (...args: any[]) => void>>;
type _Action_setCreateMenuItemStatus = Assert<Assignable<typeof page.setCreateMenuItemStatus, (...args: any[]) => void>>;
type _Handler_handleCreateMenuItemStatusChange = Assert<Assignable<typeof page.handleCreateMenuItemStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateMenuItemName = Assert<Assignable<typeof page.setUpdateMenuItemName, (...args: any[]) => void>>;
type _Handler_handleUpdateMenuItemNameChange = Assert<Assignable<typeof page.handleUpdateMenuItemNameChange, (...args: any[]) => void>>;
type _Action_setUpdateMenuItemCategory = Assert<Assignable<typeof page.setUpdateMenuItemCategory, (...args: any[]) => void>>;
type _Handler_handleUpdateMenuItemCategoryChange = Assert<Assignable<typeof page.handleUpdateMenuItemCategoryChange, (...args: any[]) => void>>;
type _Action_setUpdateMenuItemPrice = Assert<Assignable<typeof page.setUpdateMenuItemPrice, (...args: any[]) => void>>;
type _Handler_handleUpdateMenuItemPriceChange = Assert<Assignable<typeof page.handleUpdateMenuItemPriceChange, (...args: any[]) => void>>;
type _Action_setUpdateMenuItemDescription = Assert<Assignable<typeof page.setUpdateMenuItemDescription, (...args: any[]) => void>>;
type _Handler_handleUpdateMenuItemDescriptionChange = Assert<Assignable<typeof page.handleUpdateMenuItemDescriptionChange, (...args: any[]) => void>>;
type _Action_setUpdateMenuItemStatus = Assert<Assignable<typeof page.setUpdateMenuItemStatus, (...args: any[]) => void>>;
type _Handler_handleUpdateMenuItemStatusChange = Assert<Assignable<typeof page.handleUpdateMenuItemStatusChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemMenuItemId = Assert<Assignable<typeof page.setDeleteMenuItemMenuItemId, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemMenuItemIdChange = Assert<Assignable<typeof page.handleDeleteMenuItemMenuItemIdChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemName = Assert<Assignable<typeof page.setDeleteMenuItemName, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemNameChange = Assert<Assignable<typeof page.handleDeleteMenuItemNameChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemCategory = Assert<Assignable<typeof page.setDeleteMenuItemCategory, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemCategoryChange = Assert<Assignable<typeof page.handleDeleteMenuItemCategoryChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemPrice = Assert<Assignable<typeof page.setDeleteMenuItemPrice, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemPriceChange = Assert<Assignable<typeof page.handleDeleteMenuItemPriceChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemDescription = Assert<Assignable<typeof page.setDeleteMenuItemDescription, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemDescriptionChange = Assert<Assignable<typeof page.handleDeleteMenuItemDescriptionChange, (...args: any[]) => void>>;
type _Action_setDeleteMenuItemStatus = Assert<Assignable<typeof page.setDeleteMenuItemStatus, (...args: any[]) => void>>;
type _Handler_handleDeleteMenuItemStatusChange = Assert<Assignable<typeof page.handleDeleteMenuItemStatusChange, (...args: any[]) => void>>;

export {};