/// <mls fileReference="_102049_/l2/petShop/web/shared/productManagement.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { PetShopProductManagementBase } from './productManagement.js';
import type { PetShopBrowseProductsInput, PetShopBrowseProductsOutput, PetShopCreateProductInput, PetShopCreateProductOutput, PetShopSetProductHighlightsInput, PetShopSetProductHighlightsOutput, PetShopUpdateProductInput, PetShopUpdateProductOutput } from '../contracts/productManagement.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: PetShopProductManagementBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_browseProductsState = Assert<Assignable<typeof page.browseProductsState, "idle" | "loading" | "success" | "error">>;
type _State_browseProductsSearchTerm = Assert<Assignable<typeof page.browseProductsSearchTerm, string | PetShopBrowseProductsInput["searchTerm"]>>;
type _State_browseProductsPetTypeId = Assert<Assignable<typeof page.browseProductsPetTypeId, string | PetShopBrowseProductsInput["petTypeId"]>>;
type _State_browseProductsCategoryId = Assert<Assignable<typeof page.browseProductsCategoryId, string | PetShopBrowseProductsInput["categoryId"]>>;
type _State_browseProductsPriceMin = Assert<Assignable<typeof page.browseProductsPriceMin, string | PetShopBrowseProductsInput["priceMin"]>>;
type _State_browseProductsPriceMax = Assert<Assignable<typeof page.browseProductsPriceMax, string | PetShopBrowseProductsInput["priceMax"]>>;
type _State_browseProductsStatus = Assert<Assignable<typeof page.browseProductsStatus, string | PetShopBrowseProductsInput["status"]>>;
type _State_browseProductsHighlighted = Assert<Assignable<typeof page.browseProductsHighlighted, string | PetShopBrowseProductsInput["highlighted"]>>;
type _State_browseProductsData = Assert<Assignable<typeof page.browseProductsData, unknown[] | PetShopBrowseProductsOutput>>;
type _State_createProductState = Assert<Assignable<typeof page.createProductState, "idle" | "loading" | "success" | "error">>;
type _State_createProductName = Assert<Assignable<typeof page.createProductName, string | PetShopCreateProductInput["name"]>>;
type _State_createProductDescription = Assert<Assignable<typeof page.createProductDescription, string | PetShopCreateProductInput["description"]>>;
type _State_createProductPrice = Assert<Assignable<typeof page.createProductPrice, string | PetShopCreateProductInput["price"]>>;
type _State_createProductPetTypeId = Assert<Assignable<typeof page.createProductPetTypeId, string | PetShopCreateProductInput["petTypeId"]>>;
type _State_createProductCategoryId = Assert<Assignable<typeof page.createProductCategoryId, string | PetShopCreateProductInput["categoryId"]>>;
type _State_createProductHighlighted = Assert<Assignable<typeof page.createProductHighlighted, string | PetShopCreateProductInput["highlighted"]>>;
type _State_createProductStatus = Assert<Assignable<typeof page.createProductStatus, string | PetShopCreateProductInput["status"]>>;
type _State_createProductOutput = Assert<Assignable<typeof page.createProductOutput, PetShopCreateProductOutput | null>>;
type _State_createProductError = Assert<Assignable<typeof page.createProductError, string>>;
type _State_updateProductState = Assert<Assignable<typeof page.updateProductState, "idle" | "loading" | "success" | "error">>;
type _State_updateProductProductId = Assert<Assignable<typeof page.updateProductProductId, string | PetShopUpdateProductInput["productId"]>>;
type _State_updateProductName = Assert<Assignable<typeof page.updateProductName, string | PetShopUpdateProductInput["name"]>>;
type _State_updateProductDescription = Assert<Assignable<typeof page.updateProductDescription, string | PetShopUpdateProductInput["description"]>>;
type _State_updateProductPrice = Assert<Assignable<typeof page.updateProductPrice, string | PetShopUpdateProductInput["price"]>>;
type _State_updateProductPetTypeId = Assert<Assignable<typeof page.updateProductPetTypeId, string | PetShopUpdateProductInput["petTypeId"]>>;
type _State_updateProductCategoryId = Assert<Assignable<typeof page.updateProductCategoryId, string | PetShopUpdateProductInput["categoryId"]>>;
type _State_updateProductHighlighted = Assert<Assignable<typeof page.updateProductHighlighted, string | PetShopUpdateProductInput["highlighted"]>>;
type _State_updateProductStatus = Assert<Assignable<typeof page.updateProductStatus, string | PetShopUpdateProductInput["status"]>>;
type _State_updateProductOutput = Assert<Assignable<typeof page.updateProductOutput, PetShopUpdateProductOutput | null>>;
type _State_updateProductError = Assert<Assignable<typeof page.updateProductError, string>>;
type _State_setProductHighlightsState = Assert<Assignable<typeof page.setProductHighlightsState, "idle" | "loading" | "success" | "error">>;
type _State_setProductHighlightsProductIds = Assert<Assignable<typeof page.setProductHighlightsProductIds, string | PetShopSetProductHighlightsInput["productIds"]>>;
type _State_setProductHighlightsHighlighted = Assert<Assignable<typeof page.setProductHighlightsHighlighted, string | PetShopSetProductHighlightsInput["highlighted"]>>;
type _State_setProductHighlightsOutput = Assert<Assignable<typeof page.setProductHighlightsOutput, PetShopSetProductHighlightsOutput | null>>;
type _State_setProductHighlightsError = Assert<Assignable<typeof page.setProductHighlightsError, string>>;
type _Action_loadBrowseProducts = Assert<Assignable<typeof page.loadBrowseProducts, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsClick = Assert<Assignable<typeof page.handleBrowseProductsClick, (...args: any[]) => unknown>>;
type _Action_createProduct = Assert<Assignable<typeof page.createProduct, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductClick = Assert<Assignable<typeof page.handleCreateProductClick, (...args: any[]) => unknown>>;
type _Action_updateProduct = Assert<Assignable<typeof page.updateProduct, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductClick = Assert<Assignable<typeof page.handleUpdateProductClick, (...args: any[]) => unknown>>;
type _Action_setProductHighlights = Assert<Assignable<typeof page.setProductHighlights, (...args: any[]) => unknown>>;
type _Handler_handleSetProductHighlightsClick = Assert<Assignable<typeof page.handleSetProductHighlightsClick, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsSearchTerm = Assert<Assignable<typeof page.setBrowseProductsSearchTerm, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsSearchTermChange = Assert<Assignable<typeof page.handleBrowseProductsSearchTermChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsPetTypeId = Assert<Assignable<typeof page.setBrowseProductsPetTypeId, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsPetTypeIdChange = Assert<Assignable<typeof page.handleBrowseProductsPetTypeIdChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsCategoryId = Assert<Assignable<typeof page.setBrowseProductsCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsCategoryIdChange = Assert<Assignable<typeof page.handleBrowseProductsCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsPriceMin = Assert<Assignable<typeof page.setBrowseProductsPriceMin, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsPriceMinChange = Assert<Assignable<typeof page.handleBrowseProductsPriceMinChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsPriceMax = Assert<Assignable<typeof page.setBrowseProductsPriceMax, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsPriceMaxChange = Assert<Assignable<typeof page.handleBrowseProductsPriceMaxChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsStatus = Assert<Assignable<typeof page.setBrowseProductsStatus, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsStatusChange = Assert<Assignable<typeof page.handleBrowseProductsStatusChange, (...args: any[]) => unknown>>;
type _Action_setBrowseProductsHighlighted = Assert<Assignable<typeof page.setBrowseProductsHighlighted, (...args: any[]) => unknown>>;
type _Handler_handleBrowseProductsHighlightedChange = Assert<Assignable<typeof page.handleBrowseProductsHighlightedChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductName = Assert<Assignable<typeof page.setCreateProductName, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductNameChange = Assert<Assignable<typeof page.handleCreateProductNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductDescription = Assert<Assignable<typeof page.setCreateProductDescription, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductDescriptionChange = Assert<Assignable<typeof page.handleCreateProductDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductPrice = Assert<Assignable<typeof page.setCreateProductPrice, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductPriceChange = Assert<Assignable<typeof page.handleCreateProductPriceChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductPetTypeId = Assert<Assignable<typeof page.setCreateProductPetTypeId, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductPetTypeIdChange = Assert<Assignable<typeof page.handleCreateProductPetTypeIdChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductCategoryId = Assert<Assignable<typeof page.setCreateProductCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductCategoryIdChange = Assert<Assignable<typeof page.handleCreateProductCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductHighlighted = Assert<Assignable<typeof page.setCreateProductHighlighted, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductHighlightedChange = Assert<Assignable<typeof page.handleCreateProductHighlightedChange, (...args: any[]) => unknown>>;
type _Action_setCreateProductStatus = Assert<Assignable<typeof page.setCreateProductStatus, (...args: any[]) => unknown>>;
type _Handler_handleCreateProductStatusChange = Assert<Assignable<typeof page.handleCreateProductStatusChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductProductId = Assert<Assignable<typeof page.setUpdateProductProductId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductProductIdChange = Assert<Assignable<typeof page.handleUpdateProductProductIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductName = Assert<Assignable<typeof page.setUpdateProductName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductNameChange = Assert<Assignable<typeof page.handleUpdateProductNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductDescription = Assert<Assignable<typeof page.setUpdateProductDescription, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductDescriptionChange = Assert<Assignable<typeof page.handleUpdateProductDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductPrice = Assert<Assignable<typeof page.setUpdateProductPrice, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductPriceChange = Assert<Assignable<typeof page.handleUpdateProductPriceChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductPetTypeId = Assert<Assignable<typeof page.setUpdateProductPetTypeId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductPetTypeIdChange = Assert<Assignable<typeof page.handleUpdateProductPetTypeIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductCategoryId = Assert<Assignable<typeof page.setUpdateProductCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductCategoryIdChange = Assert<Assignable<typeof page.handleUpdateProductCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductHighlighted = Assert<Assignable<typeof page.setUpdateProductHighlighted, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductHighlightedChange = Assert<Assignable<typeof page.handleUpdateProductHighlightedChange, (...args: any[]) => unknown>>;
type _Action_setUpdateProductStatus = Assert<Assignable<typeof page.setUpdateProductStatus, (...args: any[]) => unknown>>;
type _Handler_handleUpdateProductStatusChange = Assert<Assignable<typeof page.handleUpdateProductStatusChange, (...args: any[]) => unknown>>;
type _Action_setSetProductHighlightsProductIds = Assert<Assignable<typeof page.setSetProductHighlightsProductIds, (...args: any[]) => unknown>>;
type _Handler_handleSetProductHighlightsProductIdsChange = Assert<Assignable<typeof page.handleSetProductHighlightsProductIdsChange, (...args: any[]) => unknown>>;
type _Action_setSetProductHighlightsHighlighted = Assert<Assignable<typeof page.setSetProductHighlightsHighlighted, (...args: any[]) => unknown>>;
type _Handler_handleSetProductHighlightsHighlightedChange = Assert<Assignable<typeof page.handleSetProductHighlightsHighlightedChange, (...args: any[]) => unknown>>;

export {};