/// <mls fileReference="_102049_/l2/petShop/web/shared/shiftManagement.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { PetShopShiftManagementBase } from './shiftManagement.js';
import type { PetShopBrowseShiftsInput, PetShopBrowseShiftsOutput, PetShopCreateShiftInput, PetShopCreateShiftOutput, PetShopUpdateShiftInput, PetShopUpdateShiftOutput } from '../contracts/shiftManagement.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: PetShopShiftManagementBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_browseShiftsState = Assert<Assignable<typeof page.browseShiftsState, "idle" | "loading" | "success" | "error">>;
type _State_browseShiftsActiveFilter = Assert<Assignable<typeof page.browseShiftsActiveFilter, string | PetShopBrowseShiftsInput["activeFilter"]>>;
type _State_browseShiftsData = Assert<Assignable<typeof page.browseShiftsData, PetShopBrowseShiftsOutput>>;
type _State_createShiftState = Assert<Assignable<typeof page.createShiftState, "idle" | "loading" | "success" | "error">>;
type _State_createShiftName = Assert<Assignable<typeof page.createShiftName, string | PetShopCreateShiftInput["name"]>>;
type _State_createShiftStartTime = Assert<Assignable<typeof page.createShiftStartTime, string | PetShopCreateShiftInput["startTime"]>>;
type _State_createShiftEndTime = Assert<Assignable<typeof page.createShiftEndTime, string | PetShopCreateShiftInput["endTime"]>>;
type _State_createShiftMonday = Assert<Assignable<typeof page.createShiftMonday, string | PetShopCreateShiftInput["monday"]>>;
type _State_createShiftTuesday = Assert<Assignable<typeof page.createShiftTuesday, string | PetShopCreateShiftInput["tuesday"]>>;
type _State_createShiftWednesday = Assert<Assignable<typeof page.createShiftWednesday, string | PetShopCreateShiftInput["wednesday"]>>;
type _State_createShiftThursday = Assert<Assignable<typeof page.createShiftThursday, string | PetShopCreateShiftInput["thursday"]>>;
type _State_createShiftFriday = Assert<Assignable<typeof page.createShiftFriday, string | PetShopCreateShiftInput["friday"]>>;
type _State_createShiftSaturday = Assert<Assignable<typeof page.createShiftSaturday, string | PetShopCreateShiftInput["saturday"]>>;
type _State_createShiftSunday = Assert<Assignable<typeof page.createShiftSunday, string | PetShopCreateShiftInput["sunday"]>>;
type _State_createShiftActive = Assert<Assignable<typeof page.createShiftActive, string | PetShopCreateShiftInput["active"]>>;
type _State_createShiftOutput = Assert<Assignable<typeof page.createShiftOutput, PetShopCreateShiftOutput | null>>;
type _State_createShiftError = Assert<Assignable<typeof page.createShiftError, string>>;
type _State_updateShiftState = Assert<Assignable<typeof page.updateShiftState, "idle" | "loading" | "success" | "error">>;
type _State_updateShiftShiftId = Assert<Assignable<typeof page.updateShiftShiftId, string | PetShopUpdateShiftInput["shiftId"]>>;
type _State_updateShiftName = Assert<Assignable<typeof page.updateShiftName, string | PetShopUpdateShiftInput["name"]>>;
type _State_updateShiftStartTime = Assert<Assignable<typeof page.updateShiftStartTime, string | PetShopUpdateShiftInput["startTime"]>>;
type _State_updateShiftEndTime = Assert<Assignable<typeof page.updateShiftEndTime, string | PetShopUpdateShiftInput["endTime"]>>;
type _State_updateShiftMonday = Assert<Assignable<typeof page.updateShiftMonday, string | PetShopUpdateShiftInput["monday"]>>;
type _State_updateShiftTuesday = Assert<Assignable<typeof page.updateShiftTuesday, string | PetShopUpdateShiftInput["tuesday"]>>;
type _State_updateShiftWednesday = Assert<Assignable<typeof page.updateShiftWednesday, string | PetShopUpdateShiftInput["wednesday"]>>;
type _State_updateShiftThursday = Assert<Assignable<typeof page.updateShiftThursday, string | PetShopUpdateShiftInput["thursday"]>>;
type _State_updateShiftFriday = Assert<Assignable<typeof page.updateShiftFriday, string | PetShopUpdateShiftInput["friday"]>>;
type _State_updateShiftSaturday = Assert<Assignable<typeof page.updateShiftSaturday, string | PetShopUpdateShiftInput["saturday"]>>;
type _State_updateShiftSunday = Assert<Assignable<typeof page.updateShiftSunday, string | PetShopUpdateShiftInput["sunday"]>>;
type _State_updateShiftActive = Assert<Assignable<typeof page.updateShiftActive, string | PetShopUpdateShiftInput["active"]>>;
type _State_updateShiftOutput = Assert<Assignable<typeof page.updateShiftOutput, PetShopUpdateShiftOutput | null>>;
type _State_updateShiftError = Assert<Assignable<typeof page.updateShiftError, string>>;
type _Action_loadBrowseShifts = Assert<Assignable<typeof page.loadBrowseShifts, (...args: any[]) => unknown>>;
type _Handler_handleBrowseShiftsClick = Assert<Assignable<typeof page.handleBrowseShiftsClick, (...args: any[]) => unknown>>;
type _Action_createShift = Assert<Assignable<typeof page.createShift, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftClick = Assert<Assignable<typeof page.handleCreateShiftClick, (...args: any[]) => unknown>>;
type _Action_updateShift = Assert<Assignable<typeof page.updateShift, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftClick = Assert<Assignable<typeof page.handleUpdateShiftClick, (...args: any[]) => unknown>>;
type _Action_setBrowseShiftsActiveFilter = Assert<Assignable<typeof page.setBrowseShiftsActiveFilter, (...args: any[]) => unknown>>;
type _Handler_handleBrowseShiftsActiveFilterChange = Assert<Assignable<typeof page.handleBrowseShiftsActiveFilterChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftName = Assert<Assignable<typeof page.setCreateShiftName, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftNameChange = Assert<Assignable<typeof page.handleCreateShiftNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftStartTime = Assert<Assignable<typeof page.setCreateShiftStartTime, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftStartTimeChange = Assert<Assignable<typeof page.handleCreateShiftStartTimeChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftEndTime = Assert<Assignable<typeof page.setCreateShiftEndTime, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftEndTimeChange = Assert<Assignable<typeof page.handleCreateShiftEndTimeChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftMonday = Assert<Assignable<typeof page.setCreateShiftMonday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftMondayChange = Assert<Assignable<typeof page.handleCreateShiftMondayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftTuesday = Assert<Assignable<typeof page.setCreateShiftTuesday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftTuesdayChange = Assert<Assignable<typeof page.handleCreateShiftTuesdayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftWednesday = Assert<Assignable<typeof page.setCreateShiftWednesday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftWednesdayChange = Assert<Assignable<typeof page.handleCreateShiftWednesdayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftThursday = Assert<Assignable<typeof page.setCreateShiftThursday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftThursdayChange = Assert<Assignable<typeof page.handleCreateShiftThursdayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftFriday = Assert<Assignable<typeof page.setCreateShiftFriday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftFridayChange = Assert<Assignable<typeof page.handleCreateShiftFridayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftSaturday = Assert<Assignable<typeof page.setCreateShiftSaturday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftSaturdayChange = Assert<Assignable<typeof page.handleCreateShiftSaturdayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftSunday = Assert<Assignable<typeof page.setCreateShiftSunday, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftSundayChange = Assert<Assignable<typeof page.handleCreateShiftSundayChange, (...args: any[]) => unknown>>;
type _Action_setCreateShiftActive = Assert<Assignable<typeof page.setCreateShiftActive, (...args: any[]) => unknown>>;
type _Handler_handleCreateShiftActiveChange = Assert<Assignable<typeof page.handleCreateShiftActiveChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftShiftId = Assert<Assignable<typeof page.setUpdateShiftShiftId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftShiftIdChange = Assert<Assignable<typeof page.handleUpdateShiftShiftIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftName = Assert<Assignable<typeof page.setUpdateShiftName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftNameChange = Assert<Assignable<typeof page.handleUpdateShiftNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftStartTime = Assert<Assignable<typeof page.setUpdateShiftStartTime, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftStartTimeChange = Assert<Assignable<typeof page.handleUpdateShiftStartTimeChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftEndTime = Assert<Assignable<typeof page.setUpdateShiftEndTime, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftEndTimeChange = Assert<Assignable<typeof page.handleUpdateShiftEndTimeChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftMonday = Assert<Assignable<typeof page.setUpdateShiftMonday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftMondayChange = Assert<Assignable<typeof page.handleUpdateShiftMondayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftTuesday = Assert<Assignable<typeof page.setUpdateShiftTuesday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftTuesdayChange = Assert<Assignable<typeof page.handleUpdateShiftTuesdayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftWednesday = Assert<Assignable<typeof page.setUpdateShiftWednesday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftWednesdayChange = Assert<Assignable<typeof page.handleUpdateShiftWednesdayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftThursday = Assert<Assignable<typeof page.setUpdateShiftThursday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftThursdayChange = Assert<Assignable<typeof page.handleUpdateShiftThursdayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftFriday = Assert<Assignable<typeof page.setUpdateShiftFriday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftFridayChange = Assert<Assignable<typeof page.handleUpdateShiftFridayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftSaturday = Assert<Assignable<typeof page.setUpdateShiftSaturday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftSaturdayChange = Assert<Assignable<typeof page.handleUpdateShiftSaturdayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftSunday = Assert<Assignable<typeof page.setUpdateShiftSunday, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftSundayChange = Assert<Assignable<typeof page.handleUpdateShiftSundayChange, (...args: any[]) => unknown>>;
type _Action_setUpdateShiftActive = Assert<Assignable<typeof page.setUpdateShiftActive, (...args: any[]) => unknown>>;
type _Handler_handleUpdateShiftActiveChange = Assert<Assignable<typeof page.handleUpdateShiftActiveChange, (...args: any[]) => unknown>>;

export {};